# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.22
# 
# >> macros
# << macros

Name:       xorg-x11-proto-glproto
Summary:    X.Org X11 Protocol glproto
Version:    1.4.13
Release:    0
Group:      Development/System
License:    MIT
URL:        http://www.x.org
Source0:    http://xorg.freedesktop.org/releases/individual/proto/glproto-%{version}.tar.bz2
Source100:  xorg-x11-proto-glproto.yaml
Patch0:     0001-Revert-glxproto-make-GLX-swap-event-struct-match-spe.patch
Patch1:     0002-glproto-add-a-new-GLXBufferSwapComplete-struct-that-.patch
Provides:   glproto


%description
glproto is the protocol for the client to send 3D rendering commands to the X server.



%prep
%setup -q -n glproto-%{version}

# 0001-Revert-glxproto-make-GLX-swap-event-struct-match-spe.patch
%patch0 -p1
# 0002-glproto-add-a-new-GLXBufferSwapComplete-struct-that-.patch
%patch1 -p1
# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static \
    --libdir=%{_datadir}

make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post






%files
%defattr(-,root,root,-)
# >> files
%{_datadir}/pkgconfig/glproto.pc
%{_includedir}/GL/glxmd.h
%{_includedir}/GL/glxtokens.h
%{_includedir}/GL/glxproto.h
%{_includedir}/GL/internal
%{_includedir}/GL/internal/glcore.h
%{_includedir}/GL/glxint.h
# << files


